### PR TITLE
add missing type

### PR DESCRIPTION
**Pull request by yocontra**
you forgot linestring! also reorganized the list

### CODE REVIEW

**Comment by yocontra** [comment]
Ping - any way I can help get this published?

**Comment by ingalls** [comment]
Hey @contra Repos in https://github.com/cutting-room-floor are not being maintained by any organization or individual and are up for grabs. If you would like ownership of this module and are interested in future maintenance I am happy to transfer it to your account and remove the copy in cutting-room-floor.

**Comment by yocontra** [comment]
@ingalls Okay, we can do that - my npm username is contra and you can transfer it to this github account if you'd like. Could you merge this first so I can delete my fork? Thanks

**Comment by ingalls** [comment]
Hey @contra You're PR is merged, give me a shout here when you have deleted the `is-geojson` repo from your account and I will transfer ownership.

**Comment by yocontra** [comment]
@ingalls I think it might make sense for me to publish from the fork instead instead of transferring the whole repo. Links back to the OG source as well. LMK when you add me to the npm.

**Comment by ingalls** [comment]
@contra As I said before, all repos in https://github.com/cutting-room-floor are abandoned and up for adoption. I was happy to merge your PR to make way for a transfer to your account but don't manage, review, or publish changes to repos both here or their associated NPM packages.

I am happy to transfer ownership of the repo to avoid confusion and show that the new maintainer is not simply a fork but taking on the torch as it were.

**Comment by yocontra** [comment]
@ingalls Alright, should be ready to transfer the repo. Do you have access to do the npm ownership as well?

**Comment by ingalls** [comment]
I'm afraid Github doesn't allow transfers unless the user or org that it is being transferred too does not have a associated fork. Since the `is-geojson-fork` is still linked to this repo Github won't allow the transfer.

The two options are:

- Delete the `is-geojson-fork` repo entirely
- Delete the GH managed repo, then create a new repo via the web interface and push back up your local code. It will be the same git repo but since it was created as a new repo and not via the fork button it shouldn't be associated to this repo as a fork.

I personally don't have NPM access to this particular package but I'm talking to those that do to get it transferred as soon as possible.

**Comment by yocontra** [comment]
@ingalls Fork deleted

**Pull request merged**
